import { useEffect, useState } from "react";
import { getAllAlerts } from "../api/alertApi";
import Loader from "../components/common/Loader";

function AlertPage() {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [errorMessage, setErrorMessage] = useState("");

  useEffect(() => {
    loadAlerts();
  }, []);

  const loadAlerts = async () => {
    try {
      setLoading(true);
      const data = await getAllAlerts();
      setAlerts(data);
      setErrorMessage("");
    } catch (error) {
      setErrorMessage("Failed to load alerts.");
    } finally {
      setLoading(false);
    }
  };

  if (loading) return <Loader />;

  return (
    <div>
      <div className="page-header">
        <h2>Alerts</h2>
        <p>Review incident-related alerts generated by the system.</p>
      </div>

      {errorMessage && <div className="error-box">{errorMessage}</div>}

      <div className="panel-card">
        <div className="panel-header">
          <h3>Alert Records</h3>
        </div>

        <div className="table-wrapper">
          <table className="custom-table">
            <thead>
              <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Message</th>
                <th>Status</th>
                <th>Incident ID</th>
                <th>Created At</th>
              </tr>
            </thead>
            <tbody>
              {alerts.length > 0 ? (
                alerts.map((alert) => (
                  <tr key={alert.id}>
                    <td>{alert.id}</td>
                    <td>{alert.title}</td>
                    <td>{alert.message}</td>
                    <td>{alert.status}</td>
                    <td>{alert.incidentId || "-"}</td>
                    <td>{alert.createdAt || "-"}</td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="6">No alerts found.</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

export default AlertPage;