import React, { useEffect, useState } from "react";
import { getAlerts } from "../api/alertApi";
import Loader from "../components/common/Loader";
const AlertPage = () => {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { getAlerts().then(setAlerts).finally(() => setLoading(false)); }, []);
  if (loading) return <Loader />;
  return (
    <div className="rm-page-card">
      <div className="rm-section-head"><h2>Alerts</h2><p>Review incident-related alerts generated by the system.</p></div>
      <div className="rm-table-wrap">
        <table className="rm-app-table">
          <thead><tr><th>ID</th><th>Title</th><th>Message</th><th>Status</th><th>Incident ID</th><th>Created At</th></tr></thead>
          <tbody>
            {alerts.length === 0 ? <tr><td colSpan="6">No alerts available.</td></tr>
              : alerts.map(a => <tr key={a.id}><td>{a.id}</td><td>{a.title}</td><td>{a.message}</td><td>{a.status}</td><td>{a.incidentId}</td><td>{a.createdAt}</td></tr>)}
          </tbody>
        </table>
      </div>
    </div>
  );
};
export default AlertPage;
