import React, { useEffect, useState } from "react";
import { getAlerts } from "../api/alertApi";
import Loader from "../components/common/Loader";

const AlertPage = () => {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadAlerts = async () => {
      try {
        const data = await getAlerts();
        setAlerts(data);
      } finally {
        setLoading(false);
      }
    };

    loadAlerts();
  }, []);

  if (loading) return <Loader />;

  return (
    <div className="page-card">
      <div className="section-head">
        <h2>Alerts</h2>
        <p>Review incident-related alerts generated by the system.</p>
      </div>

      <div className="table-wrap">
        <table className="app-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Title</th>
              <th>Message</th>
              <th>Status</th>
              <th>Incident ID</th>
              <th>Created At</th>
            </tr>
          </thead>
          <tbody>
            {alerts.length === 0 ? (
              <tr>
                <td colSpan="6">No alerts available.</td>
              </tr>
            ) : (
              alerts.map((alert) => (
                <tr key={alert.id}>
                  <td>{alert.id}</td>
                  <td>{alert.title}</td>
                  <td>{alert.message}</td>
                  <td>{alert.status}</td>
                  <td>{alert.incidentId}</td>
                  <td>{alert.createdAt}</td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default AlertPage;